#!/bin/sh

# Script to start Yousician with the MP3 transcode hack put it, together with
# 'yousician_transcode.so' in the Yousician directory (where the 'Yousician
# Launcher executable is)

# transcoder command to use

YOUSICIAN_TRANSCODER="sox -t mp3 - -t ogg -"
#YOUSICIAN_TRANSCODER="ffmpeg -f mp3 -i - -f ogg -"

#----------------------------------------------------

myname="$(readlink -f "$0")"
[ -e "$myname" ] || exit 1

dir="$(dirname "$myname")"
[ -d "$dir" ] || exit 1

export YOUSICIAN_TRANSCODER

# $dir may contain spaces, cannot be used in $LD_PRELOAD
# use the config dir instead – it is always there and should not contain spaces
config_dir="${XDG_CONFIG_HOME:-$HOME/.config}"/unity3d/Yousician/Yousician
mkdir -p "$config_dir"
ln -s "$dir/yousician_transcode.so" "$config_dir/yousician_transcode.so"
export LD_PRELOAD="$config_dir/yousician_transcode.so"
"$dir/Yousician Launcher"
